config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="headSec">
      <h1>Wednesday Night Golf Goodies</h1>  
      <ul>
        <li><%= link_to "HOME", "/" %> </li>
        <li><%= link_to "ABOUT", about_path %> </li>
        <li><%= link_to "HELP", help_path %> </li>
      </ul>
    
    </header>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <footer class="footer">
      <h1>Look Im At The Bottom...</h1>
      
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="mainCont">
    
    <h1>HOME</h1>

<p>Welcome this is the home page ..... more to come</p>    
</div>